import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  constructor() { }

  UserServices=[
    {
      id:1,
      title:"UI/UX Design",
      description:`" UI designers are curious about the future of UI design post-COVID. So, 
                   let’s look at how it unfolds Now that the world is dealing with the COVID-19 pandemic, 
                   many or rather outbreaks in 2021.Here is what we feel is in store:
                    Improved Comfort, AR Glasses, Skeuomorphism and Flat UI continuers, Neumorphism is a fresh 
                    take at making experiences realistic yet unique, Type Designs and Large Images, Voice User
                     Interface and lot more.Orido is a leading web design agency with an award-winning design "`,
      serviceImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFwIGhzU4jos_SzGVL04_44XGuAX7HPo0EAw&usqp=CAU"
    },
    {
      id:2,
      title:"User Research",
      description:`"The world is dealing with the COVID-19 pandemic, User Research
                    many UI designers are curious about the future of UI design post-COVID. So, 
                    let’s look at how it unfolds or rather outbreaks in 2021.Here is what we feel is in store:
                    Improved Comfort, AR Glasses, Skeuomorphism and Flat UI continuers, Neumorphism is a fresh 
                    take at making experiences realistic yet unique, Type Designs and Large Images, Voice User
                      Interface and lot more.Orido is a leading web design agency with an award-winning design "`,
      serviceImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTue2NN0SsfMgcX0RIgJyCiek9OF9B3up4dJQ&usqp=CAU" 
    },
    {
      id:3,
      title:"UI Animation",
      description:`"Here is what we feel is in store:
                  Improved Comfort, AR Glasses, Skeuomorphism and Flat UI continuers, Neumorphism is a fresh 
                  take at making experiences realistic yet unique, Type Designs and Large Images, Voice User
                    Interface and lot more.Orido is a leading web design agency with an award-winning designNow that the world is dealing with the COVID-19 pandemic, 
                    many UI designers are curious about the future of UI design post-COVID. So, 
                    let’s look at how it unfolds or rather outbreaks in 2021. "`,
      serviceImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsYy-r1rfJFOEMWdTrLbRwXz50YDsbmLUdfg&usqp=CAU"
    },
    {
      id:4,
      title:"Product Design",
      description:`"Now that the world is dealing with the COVID-19 pandemic, 
                    many UI designers are curious about the future of UI design post-COVID. So, 
                    let’s look at how it unfolds or rather outbreaks in 2021.Here is what we feel is in store:
                    Improved Comfort, AR Glasses, Skeuomorphism and Flat UI continuers, Neumorphism is a fresh 
                    take at making experiences realistic yet unique, Type Designs and Large Images, Voice User
                      Interface and lot more.Orido is a leading web design agency with an award-winning design "`,
      serviceImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmlmDJ3TVh-MjOjmNDkAR2TxrZfvqdAij0Dw&usqp=CAU"
    }
  ];

  projectData=[
    {
      name:"Cloud Kitchen",
      description:`"A cloud kitchen utilizes a commercial kitchen for the purpose of preparing food 
      for delivery or takeout only, with no dine-in customers.
      Cloud kitchens enable restauranteurs to expand an existing restaurant or start a virtual brand 
      at minimal cost. This provides restauranteurs with the opportunity to scale, explore new markets, or
       trial new concepts. Many restaurants use cloud kitchens as an experimental space, optimizing staff and 
       inventory while testing new ideas. There are several types of cloud kitchen business models:"`,
       images:["./assets/brooke-lark-HlNcigvUi4Q-unsplash.jpg","./assets/anna-pelzer-IGfIGP5ONV0-unsplash.jpg"],
    },
    {
      name:"Document e-Sign",
      description:`"An electronic signature is a broad term for any electronic process that indicates 
      acceptance of an agreement or a record. A digital signature refers to a more secure electronic
       signature that is generated using a digital certificate and cryptographically bound to the document 
       using public key infrastructure (PKI).Easy and secure way to digitally sign information anywhere,
        anytime - eSign is an online service for electronic signatures without using physical cryptographic"`,
      images:["https://orido-react.vercel.app/img/news/2.jpg","https://orido-react.vercel.app/img/news/3.jpg"]
    },
    {
      name:"AM Social feed",
      description:`"Social media feeds are widgets generated by social media aggregators that contain content
       from various social media accounts. For example, social media feeds can display all your brand’s content from
       various social media platforms in one wall-like layout.To do this, you will need social media aggregator that will
       get access to your social media accounts and get all the mentioned content from other users who posted about your brand.
       In more detail, social media aggregators are the tools that have API access to these major platforms and provide the ability
        to generate and sync tons of content."`,
      images:["https://solwincdn-79e1.kxcdn.com/wp-content/uploads/2020/05/Social-Media-Embedding.png","https://images.cloudflareapps.com/uNHha5iLSg28858aqQTL_social%20feed%201%20(1)%20(3).png"]
    }

  ]
}
